/**
 * Карточки портфолио — добавляйте новые работы в масс portfolioItems.
 *
 * category: 'texts' | 'sites' | 'automation' | 'visual' | 'craft'
 * status: 'ready' | 'testing' | 'soon' | 'developing'
 * buttonText: текст кнопки (по умолчанию «Посмотреть»)
 * buttonLink: ссылка кнопки (пока #contacts или URL работы)
 * previewLabel: подпись на заглушке превью
 */
const portfolioItems = [
  {
    id: 1,
    title: 'Калькулятор семейного бюджета',
    category: 'automation',
    categoryLabel: 'Автоматизация / Личные финансы',
    description: 'Помогает распределять доходы и расходы, видеть общую картину бюджета и планировать траты.',
    done: 'Калькулятор с разделами доходов, расходов и итоговой сводкой.',
    status: 'ready',
    statusLabel: 'Готово',
    buttonText: 'Посмотреть',
    buttonLink: 'contacts.html',
    previewLabel: 'Превью: калькулятор бюджета',
  },
  {
    id: 2,
    title: 'Калькулятор личного бюджета',
    category: 'automation',
    categoryLabel: 'Автоматизация / Личные финансы',
    description: 'Инструмент для учёта личных доходов, расходов и финансовых целей.',
    done: 'Таблица учёта с категориями и целями накопления.',
    status: 'ready',
    statusLabel: 'Готово',
    buttonText: 'Посмотреть',
    buttonLink: 'contacts.html',
    previewLabel: 'Превью: личный бюджет',
  },
  {
    id: 3,
    title: 'Калькулятор бюджета проекта',
    category: 'automation',
    categoryLabel: 'Автоматизация / Проекты',
    description: 'Помогает рассчитать расходы, резерв и итоговую сумму для проекта.',
    done: 'Расчёт статей расходов, резерва и итоговой суммы.',
    status: 'ready',
    statusLabel: 'Готово',
    buttonText: 'Посмотреть',
    buttonLink: 'contacts.html',
    previewLabel: 'Превью: бюджет проекта',
  },
  {
    id: 4,
    title: 'Калькулятор расчёта плетёного короба',
    category: 'craft',
    categoryLabel: 'Автоматизация / Для рукодельниц',
    description: 'Инструмент для расчёта параметров плетёного короба.',
    done: 'Расчёт размеров, материала и параметров короба.',
    status: 'ready',
    statusLabel: 'Готово',
    buttonText: 'Посмотреть',
    buttonLink: 'contacts.html',
    previewLabel: 'Превью: калькулятор короба',
  },
  {
    id: 5,
    title: 'Калькулятор стоимости изделия',
    category: 'craft',
    categoryLabel: 'Автоматизация / Для рукодельниц',
    description: 'Подробный расчёт материалов, времени, упаковки, наценки и итоговой цены.',
    done: 'Полный расчёт себестоимости и цены продажи.',
    status: 'testing',
    statusLabel: 'На тестировании',
    buttonText: 'Посмотреть',
    buttonLink: 'contacts.html',
    previewLabel: 'Превью: стоимость изделия',
  },
  {
    id: 6,
    title: 'Генератор идей для постов',
    category: 'automation',
    categoryLabel: 'Автоматизация / Контент',
    description: 'Автоматизированная таблица, которая помогает находить идеи для публикаций.',
    done: 'Таблица с темами, форматами и подсказками для постов.',
    status: 'ready',
    statusLabel: 'Готово',
    buttonText: 'Посмотреть',
    buttonLink: 'contacts.html',
    previewLabel: 'Превью: генератор идей',
  },
  {
    id: 7,
    title: 'Контент-таблица для ВК, Telegram и MAX',
    category: 'automation',
    categoryLabel: 'Автоматизация / Контент',
    description: 'Помогает собрать контент-план, посты и сценарии для коротких видео.',
    done: 'План публикаций, тексты постов и сценарии видео.',
    status: 'ready',
    statusLabel: 'Готово / развивается',
    buttonText: 'Посмотреть',
    buttonLink: 'contacts.html',
    previewLabel: 'Превью: контент-таблица',
  },
  {
    id: 8,
    title: 'Логотип для проекта',
    category: 'visual',
    categoryLabel: 'Визуальное оформление',
    description: 'Варианты логотипа с разным настроением: форма, цвет, идея и пример применения.',
    done: 'Несколько вариантов логотипа с примерами использования.',
    status: 'ready',
    statusLabel: 'Готово',
    buttonText: 'Посмотреть',
    buttonLink: 'contacts.html',
    previewLabel: 'Превью: логотип',
  },
  {
    id: 9,
    title: 'Описание товара для соцсетей',
    category: 'texts',
    categoryLabel: 'Тексты и смыслы',
    description: 'Текст, который помогает показать ценность товара и объяснить, почему на него стоит обратить внимание.',
    done: 'Готовый текст с акцентом на пользу и ценность.',
    status: 'soon',
    statusLabel: 'Скоро добавлю пример',
    buttonText: 'Посмотреть',
    buttonLink: 'contacts.html',
    previewLabel: 'Превью: текст товара',
  },
  {
    id: 10,
    title: 'Простая страница проекта',
    category: 'sites',
    categoryLabel: 'Сайты и веб-страницы',
    description: 'Одностраничная структура для проекта: кто вы, что предлагаете, примеры, кнопка связи.',
    done: 'Структура лендинга с блоками и формой связи.',
    status: 'soon',
    statusLabel: 'Скоро добавлю пример',
    buttonText: 'Посмотреть',
    buttonLink: 'contacts.html',
    previewLabel: 'Превью: страница проекта',
  },
];
